version: '3'
services:
  file-server:
    image: kuzudb/extension-repo
    ports:
      - "8081:80"
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=false

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=30
      - WATCHTOWER_LABEL_ENABLE=true
    labels:
      - com.centurylinklabs.watchtower.enable=true
