version: '3'
services:
  file-server:
    image: kuzudb/extension-repo
    ports:
      - "8081:80"
    restart: always
  
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: --interval 30
